version: "3.9"

services:
  app:
    build: .
    container_name: my_app
    ports:
      - "8000:8000"
    volumes:
      - .:.   # mount code to live reload
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn server:app --host 0.0.0.0 --port 8000
